# Generated by Django 2.0.5 on 2018-05-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('subject', models.CharField(max_length=20, verbose_name='标记类型')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usermarks_owned', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '用户标记',
                'verbose_name_plural': '用户标记',
                'db_table': 'base_mark_user_mark',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usermark',
            unique_together={('author', 'content_type', 'object_id', 'subject')},
        ),
    ]
