# Generated by Django 2.0.5 on 2018-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='图片名称')),
                ('image', models.ImageField(upload_to='images/', verbose_name='图片')),
                ('ext_url', models.URLField(blank=True, default='', verbose_name='外部图片链接')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'base_media_image',
            },
        ),
    ]
