# Generated by Django 2.0.5 on 2018-09-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_media', '0002_auto_20180620_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='名称')),
                ('ext_url', models.URLField(blank=True, default='', verbose_name='外部附件链接')),
                ('file', models.FileField(blank=True, upload_to='attachment/', verbose_name='上传附件')),
            ],
            options={
                'verbose_name': '附件',
                'verbose_name_plural': '附件',
                'db_table': 'base_media_attachment',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='ext_url',
            field=models.URLField(blank=True, default='', verbose_name='外部附件链接'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='名称'),
        ),
    ]
